### ISSUE TITLE
Cross-platform port

### ISSUE THREAD

**Issue by rdanbrook** [qwertymodo/msupcmplusplus#2]
Hi there,

I attempted to port this to Linux this morning, but it was non-trivial and after an hour I gave up. In theory all it should need is a few more #includes added, and removing functions that only exist in Microsoft's C library (_wremove). All of the dependencies are open source C libraries so on Linux you don't need to include those in the codebase, with the exception of the C++ json library being used here.

Thanks, I hope you decide to port this codebase in the future.

**Comment by qwertymodo** [comment]
Linux builds should work as of 56daa24986fd87343db2d2a7f6f235b29c6a11f6.  I need to spin up a fresh Linux VM to test my documentation against, but the main trick is ensuring you have all of the libSoX dependencies installed.  Check https://github.com/qwertymodo/msupcmplusplus/blob/master/3rdparty/sox/INSTALL for a list of the dependencies and make sure you install the -dev packages.  Give it a try and let me know how it goes.  Tested and working here in Windows 10 LxSS (aka "Ubuntu Bash on Windows").

**Comment by rdanbrook** [comment]
That's great news, thanks for taking the time to do this work.

I will be able to test it and tell you how it goes in a few days time. Just a few quick questions though: What was your reason for modifying sox (assuming you did)? Also, why is pulse a dependency?

**Comment by qwertymodo** [comment]
I used sox as a base because it already did almost everything I needed, and the unmodified command-line application was the core of my previous audio conversion toolchain.  When I wanted to move away from 4 separate applications glued together with a batch script, I chose libSoX as the base of the application.  The modifications I made were to add RMS normalization and MSU-1 .pcm file format support, along with Windows Unicode support.  However, I did all of my development on Windows, which is how I broke Linux support (and never bothered creating Makefiles for my own code).  Pulse is only an optional dependency for SoX itself, you can modify the main project Makefile to configure libSoX without it.  I left most of the common dependencies because with them comes support for those file types as inputs.

**Comment by qwertymodo** [comment]
See here for the optional dependencies I'm disabling by default and can be omitted (and add any you want yourself): https://github.com/qwertymodo/msupcmplusplus/blob/master/Makefile#L15
